name: Create a comment on new issues

on:
  issues:
    types: [opened]

jobs:
  comment-with-action:
    runs-on: ubuntu-latest
    steps:
      - name: dump event payload
        run: echo "${{ toJson(github.event) }}"
      - name: Create issue comment
        uses: peter-evans/create-issue-comment@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Thank you for opening this issue! We will look into it as soon as possible.
            - With Github **Markdown** :sparkles:
            - created y [create-or-update-comment][1]

            [1]:test123

          reactions: '+1'

